#include "AppGraderEffect.h"

#include <kwin/effect/effecthandler.h>
#include <kwin/effect/effectwindow.h>
#include <kwin/effect/globals.h>
#include <kwin/core/output.h>
#include <kwin/core/renderviewport.h>
#include <kwin/core/rendertarget.h>
#include <kwin/opengl/gllut3D.h>
#include <kwin/opengl/glshader.h>
#include <kwin/opengl/glshadermanager.h>

#include <QVector2D>

#include <QDir>
#include <QFile>
#include <QFileSystemWatcher>

#include <epoxy/gl.h>

#include <vector>

KWIN_EFFECT_FACTORY_SUPPORTED(AppGraderEffect, "metadata.json",
    return AppGraderEffect::supported();)

/* ── GLSL fragment shader ─────────────────────────────────────────────
 *
 * Designed to plug into KWin's ShaderTrait::MapTexture pipeline:
 *   - vertex stage is auto-generated by KWin (provides texcoord0)
 *   - the standard `sampler` and `modulation` uniforms are set by KWin
 *
 * Same legacy GLSL syntax KWin's own colorblindnesscorrection effect uses
 * (varying / texture2D / gl_FragColor). KWin's ShaderManager preprocesses
 * the source so this works in the GL 3.1 / GLSL 1.40 context too. */
static const QByteArray FRAG_SRC = QByteArrayLiteral(R"glsl(
uniform sampler2D sampler;
uniform vec4 modulation;
uniform sampler3D appgrader_lut;
uniform float appgrader_lut_size;

/* Spatial effect uniforms. All zero/identity = no-op. Floats only — vec2
 * uniforms can be flaky to set across drivers. */
uniform float appgrader_screen_w;
uniform float appgrader_screen_h;
uniform float appgrader_vig_amount;
uniform float appgrader_vig_distance;
uniform float appgrader_noise_amount;
uniform float appgrader_noise_color;
uniform float appgrader_noise_scale;
uniform float appgrader_sharpen_amount;
uniform float appgrader_clarity_amount;
uniform float appgrader_time;
uniform float appgrader_noise_static;   /* 0 = animated, 1 = freeze frame */
uniform float appgrader_noise_seed;     /* 0..1, shifts the per-cell hash */
uniform float appgrader_bloom_amount;
uniform float appgrader_bloom_threshold;
uniform float appgrader_bloom_radius;

varying vec2 texcoord0;

void main()
{
    vec4 tex = texture2D(sampler, texcoord0);
    float a = max(tex.a, 1.0/255.0);
    vec3 straight = clamp(tex.rgb / a, 0.0, 1.0);

    vec2 texelSize = 1.0 / vec2(textureSize(sampler, 0));

    /* Sharpen — 5-tap unsharp at 1-pixel radius. Always evaluated; if
     * amount==0 the (c0 - blur) term contributes zero anyway. */
    vec3 c1 = clamp(texture2D(sampler, texcoord0 + vec2( texelSize.x, 0.0)).rgb / a, 0.0, 1.0);
    vec3 c2 = clamp(texture2D(sampler, texcoord0 - vec2( texelSize.x, 0.0)).rgb / a, 0.0, 1.0);
    vec3 c3 = clamp(texture2D(sampler, texcoord0 + vec2(0.0,  texelSize.y)).rgb / a, 0.0, 1.0);
    vec3 c4 = clamp(texture2D(sampler, texcoord0 - vec2(0.0,  texelSize.y)).rgb / a, 0.0, 1.0);
    vec3 sharpBlur = (straight + c1 + c2 + c3 + c4) * 0.2;
    straight = clamp(straight + appgrader_sharpen_amount * 1.5 * (straight - sharpBlur), 0.0, 1.0);

    /* Clarity — 8-tap wider unsharp. Positive = micro-contrast,
     * negative = hazy/bloom (lerp toward blur). */
    float r = 4.0;
    vec3 c5 = clamp(texture2D(sampler, texcoord0 + vec2( r * texelSize.x,  r * texelSize.y)).rgb / a, 0.0, 1.0);
    vec3 c6 = clamp(texture2D(sampler, texcoord0 + vec2(-r * texelSize.x,  r * texelSize.y)).rgb / a, 0.0, 1.0);
    vec3 c7 = clamp(texture2D(sampler, texcoord0 + vec2( r * texelSize.x, -r * texelSize.y)).rgb / a, 0.0, 1.0);
    vec3 c8 = clamp(texture2D(sampler, texcoord0 + vec2(-r * texelSize.x, -r * texelSize.y)).rgb / a, 0.0, 1.0);
    vec3 c9 = clamp(texture2D(sampler, texcoord0 + vec2( r * texelSize.x, 0.0)).rgb / a, 0.0, 1.0);
    vec3 cA = clamp(texture2D(sampler, texcoord0 + vec2(-r * texelSize.x, 0.0)).rgb / a, 0.0, 1.0);
    vec3 cB = clamp(texture2D(sampler, texcoord0 + vec2(0.0,  r * texelSize.y)).rgb / a, 0.0, 1.0);
    vec3 cC = clamp(texture2D(sampler, texcoord0 + vec2(0.0, -r * texelSize.y)).rgb / a, 0.0, 1.0);
    vec3 wideBlur = (c5 + c6 + c7 + c8 + c9 + cA + cB + cC) * 0.125;
    float clarityPos = max(appgrader_clarity_amount, 0.0);
    float clarityNeg = max(-appgrader_clarity_amount, 0.0);
    straight = clamp(straight + clarityPos * 1.2 * (straight - wideBlur), 0.0, 1.0);
    straight = mix(straight, wideBlur, clarityNeg);

    /* Colour grade via 3D LUT. */
    float ls = (appgrader_lut_size - 1.0) / appgrader_lut_size;
    float lo = 0.5 / appgrader_lut_size;
    vec3 graded = texture3D(appgrader_lut, straight * ls + lo).rgb;

    /* Bloom — 7x7 Gaussian-weighted bright-pass, screen-blended over the
     * graded image. Mimics the Photoshop workflow of (threshold → gaussian
     * blur → screen-blend on top of the source). Each tap is bright-passed
     * (luma above threshold), weighted by a 2D Gaussian by distance, summed
     * and normalised by the total weight, then screen-blended so highlights
     * lift softly without clipping additively. Radius slider maps to a max
     * sample radius of 4..32 px; with 7 stops per axis the inter-sample gap
     * stays small enough that bilinear filtering masks the discrete pattern.
     * Gated on amount > 0 so the 49 extra taps are only paid when bloom
     * is actually enabled. */
    if (appgrader_bloom_amount > 0.001) {
        float maxR = mix(4.0, 32.0, clamp(appgrader_bloom_radius, 0.0, 1.0));
        float sigma = maxR * 0.5;                 /* kernel covers ±2σ */
        float invTwoSigSq = 1.0 / (2.0 * sigma * sigma);
        float stepPx = maxR / 3.0;                /* 7 stops over [-maxR, +maxR] */
        float thr = clamp(appgrader_bloom_threshold, 0.0, 0.999);
        float headroom = max(1.0 - thr, 0.001);

        vec3 bloomSum = vec3(0.0);
        float wSum = 0.0;
        for (int j = -3; j <= 3; j++) {
            for (int i = -3; i <= 3; i++) {
                vec2 offPx = vec2(float(i), float(j)) * stepPx;
                float r2 = dot(offPx, offPx);
                float w = exp(-r2 * invTwoSigSq);
                vec3 s = clamp(texture2D(sampler, texcoord0 + offPx * texelSize).rgb / a, 0.0, 1.0);
                float lum = dot(s, vec3(0.2126, 0.7152, 0.0722));
                float bp = max(lum - thr, 0.0) / headroom;
                bloomSum += s * bp * w;
                wSum += w;
            }
        }
        bloomSum /= max(wSum, 0.001);
        /* Screen blend: out = 1 - (1-base)(1-bloom*amount). Bright pixels
         * lift toward 1.0 instead of overshooting it. */
        vec3 bloomLayer = clamp(bloomSum * appgrader_bloom_amount * 1.5, 0.0, 1.0);
        graded = 1.0 - (1.0 - graded) * (1.0 - bloomLayer);
    }

    /* Vignette — screen-space distance from centre. */
    float scrW = max(appgrader_screen_w, 1.0);
    float scrH = max(appgrader_screen_h, 1.0);
    vec2 sUv = gl_FragCoord.xy / vec2(scrW, scrH);
    vec2 d = sUv - vec2(0.5);
    d.x *= scrW / scrH;
    float r2 = dot(d, d);
    float radius = mix(0.25, 0.9, appgrader_vig_distance);
    float fall = smoothstep(radius * radius * 0.5, radius * radius * 1.4, r2);
    graded *= 1.0 - appgrader_vig_amount * fall;
    graded = clamp(graded, 0.0, 1.0);

    /* Noise — per-cell hash. Uses Dave Hoskins's hash33 (well-distributed,
     * no visible tiling at any scale). Time goes to zero when frozen so
     * static seeds give a stable grain pattern. */
    float cellPx = 1.0 + appgrader_noise_scale * 9.0;
    vec2 cell = floor(gl_FragCoord.xy / cellPx);
    float frame = appgrader_time * (1.0 - appgrader_noise_static);
    /* Seed offsets the cell coordinate so different seeds give visually
     * distinct patterns instead of just shifted versions of the same one. */
    vec3 seedShift = appgrader_noise_seed * vec3(127.1, 311.7, 74.7);
    vec3 p3 = vec3(cell, frame) + seedShift;
    p3 = fract(p3 * vec3(0.1031, 0.1030, 0.0973));
    p3 += dot(p3, p3.yxz + 33.33);
    vec3 n = fract((p3.xxy + p3.yxx) * p3.zyx);
    float lum = (n.r + n.g + n.b) * (1.0 / 3.0);
    vec3 grain = mix(vec3(lum), n, appgrader_noise_color) - 0.5;
    graded = clamp(graded + grain * appgrader_noise_amount * 0.5, 0.0, 1.0);

    gl_FragColor = vec4(graded * tex.a, tex.a) * modulation;
}
)glsl");

/* ── Construction ─────────────────────────────────────────────────── */

AppGraderEffect::AppGraderEffect()
{
    /* Build identifier: helps verify in `journalctl --user -f` whether KWin
     * actually loaded a fresh .so after Install/Update + Reload. */
    qWarning("appgrader_lut: effect loaded, build %s %s", __DATE__, __TIME__);

    spatial_params_init(&m_spatial);
    m_clock.start();

    const QString cfgDir = QDir::homePath() + "/.config/appgrader";
    m_lutPath           = cfgDir + "/active.lut";
    m_activeTargetPath  = cfgDir + "/active_target";
    m_windowsListPath   = cfgDir + "/windows.list";
    m_spatialPath       = cfgDir + "/spatial.params";

    loadShader();
    if (!m_shader || !m_shader->isValid()) {
        qWarning("AppGraderEffect: shader compile failed — GL %s, GLSL %s",
                 glGetString(GL_VERSION),
                 glGetString(GL_SHADING_LANGUAGE_VERSION));
        return;
    }

    readActiveTarget();
    readSpatialFromFile();
    qWarning("appgrader_lut: initial spatial vig=%.2f noise=%.2f sharp=%.2f clarity=%.2f",
             m_spatial.vignette_amount, m_spatial.noise_amount,
             m_spatial.sharpen_amount, m_spatial.clarity_amount);
    if (QFile::exists(m_lutPath))
        loadLutFromFile();

    m_watcher = new QFileSystemWatcher(this);
    if (QFile::exists(m_lutPath))
        m_watcher->addPath(m_lutPath);
    if (QFile::exists(m_activeTargetPath))
        m_watcher->addPath(m_activeTargetPath);
    if (QFile::exists(m_spatialPath))
        m_watcher->addPath(m_spatialPath);
    /* Also watch the parent directory so we re-pick-up files after atomic
     * rename-replace drops the original inode. */
    m_watcher->addPath(cfgDir);
    connect(m_watcher, &QFileSystemWatcher::fileChanged, this, [this](const QString &p) {
        if (p == m_activeTargetPath) onActiveTargetFileChanged();
        else if (p == m_spatialPath) onSpatialFileChanged();
        else                          onLutFileChanged();
    });
    connect(m_watcher, &QFileSystemWatcher::directoryChanged, this, [this]() {
        onLutFileChanged();
        onActiveTargetFileChanged();
        onSpatialFileChanged();
    });

    redirectAllWindows();
    writeWindowsList();

    connect(KWin::effects, &KWin::EffectsHandler::windowAdded,
            this, &AppGraderEffect::onWindowAdded);
    connect(KWin::effects, &KWin::EffectsHandler::windowDeleted,
            this, &AppGraderEffect::onWindowDeleted);
}

AppGraderEffect::~AppGraderEffect() = default;

bool AppGraderEffect::supported()
{
    return KWin::effects->compositingType() == KWin::OpenGLCompositing
        && KWin::OffscreenEffect::supported();
}

bool AppGraderEffect::isActive() const
{
    return !m_windows.empty()
        && m_lut
        && m_shader && m_shader->isValid();
}

int AppGraderEffect::requestedEffectChainPosition() const
{
    /* Run last so we grade the final composited image (as last as we can
     * get within the per-window redirect model). */
    return 99;
}

/* ── Shader / LUT setup ───────────────────────────────────────────── */

void AppGraderEffect::loadShader()
{
    m_shader = KWin::ShaderManager::instance()->generateCustomShader(
        KWin::ShaderTrait::MapTexture, QByteArray(), FRAG_SRC);

    if (m_shader && m_shader->isValid()) {
        /* The LUT sampler always lives on texture unit 1 (unit 0 is the
         * window content, set by KWin). Tell the shader once. */
        KWin::ShaderBinder binder(m_shader.get());
        m_shader->setUniform("appgrader_lut", 1);
    }
}

void AppGraderEffect::loadLutFromFile()
{
    QFile f(m_lutPath);
    if (!f.open(QIODevice::ReadOnly)) {
        m_lut.reset();
        return;
    }

    int32_t size = 0;
    if (f.read(reinterpret_cast<char *>(&size), 4) != 4 || size < 2 || size > 256) {
        m_lut.reset();
        return;
    }

    const size_t n = (size_t)size * size * size * 3;
    const QByteArray raw = f.read((qint64)(n * sizeof(float)));
    if ((size_t)raw.size() != n * sizeof(float)) {
        m_lut.reset();
        return;
    }

    /* Copy so the lambda can capture by value safely. */
    const std::vector<float> data(
        reinterpret_cast<const float *>(raw.constData()),
        reinterpret_cast<const float *>(raw.constData()) + n);

    const int s = size;
    m_lut = KWin::GlLookUpTable3D::create(
        [data, s](size_t r, size_t g, size_t b) -> QVector3D {
            const size_t idx = (b * (size_t)s * s + g * (size_t)s + r) * 3;
            return QVector3D(data[idx], data[idx + 1], data[idx + 2]);
        },
        (size_t)size, (size_t)size, (size_t)size);

    m_lutSize = size;

    if (m_lut && m_shader && m_shader->isValid()) {
        KWin::ShaderBinder binder(m_shader.get());
        m_shader->setUniform("appgrader_lut_size", (float)m_lutSize);
    }
}

/* ── Output filtering ─────────────────────────────────────────────── */

void AppGraderEffect::readSpatialFromFile()
{
    QFile f(m_spatialPath);
    if (!f.open(QIODevice::ReadOnly)) {
        spatial_params_init(&m_spatial);
        return;
    }
    QByteArray raw = f.read(sizeof(SpatialParams));
    if ((size_t)raw.size() != sizeof(SpatialParams)) {
        spatial_params_init(&m_spatial);
        return;
    }
    memcpy(&m_spatial, raw.constData(), sizeof(SpatialParams));
    if (m_spatial.version != 1) spatial_params_init(&m_spatial);
}

void AppGraderEffect::onSpatialFileChanged()
{
    if (QFile::exists(m_spatialPath)
        && !m_watcher->files().contains(m_spatialPath))
        m_watcher->addPath(m_spatialPath);
    readSpatialFromFile();
    qWarning("appgrader_lut: spatial reload — vig=%.2f/%.2f noise=%.2f/%.2f/%.2f static=%d seed=%.2f sharp=%.2f clarity=%.2f bloom=%.2f/%.2f/%.2f",
          m_spatial.vignette_amount, m_spatial.vignette_distance,
          m_spatial.noise_amount, m_spatial.noise_color, m_spatial.noise_scale,
          (int)m_spatial.noise_static, m_spatial.noise_seed,
          m_spatial.sharpen_amount, m_spatial.clarity_amount,
          m_spatial.bloom_amount, m_spatial.bloom_threshold, m_spatial.bloom_radius);
    KWin::effects->addRepaintFull();
}

void AppGraderEffect::readActiveTarget()
{
    QFile f(m_activeTargetPath);
    if (!f.open(QIODevice::ReadOnly | QIODevice::Text)) {
        m_activeTarget.clear();   /* missing file → grade all */
        return;
    }
    m_activeTarget = QString::fromUtf8(f.readAll()).trimmed();
}

bool AppGraderEffect::shouldGrade(KWin::EffectWindow *w) const
{
    if (m_activeTarget.isEmpty()) return true;     /* unset → grade everything */
    if (!w) return false;

    if (m_activeTarget.startsWith(QLatin1String("output:"))) {
        const QStringView name = QStringView(m_activeTarget).mid(7);
        KWin::LogicalOutput *o = w->screen();
        return o && o->name() == name;
    }
    if (m_activeTarget.startsWith(QLatin1String("window:"))) {
        const QStringView uuid = QStringView(m_activeTarget).mid(7);
        return w->internalId().toString(QUuid::WithoutBraces) == uuid;
    }
    /* Backwards compatibility with the old "active_output" file format
     * that stored just the bare monitor name. */
    KWin::LogicalOutput *o = w->screen();
    return o && o->name() == m_activeTarget;
}

/* Write a snapshot of the current normal-window list so the app can
 * populate its Target dropdown. Atomic via .tmp + rename so the app
 * never reads a half-written file. Tabs in caption/class are sanitized
 * since the format is tab-delimited. */
void AppGraderEffect::writeWindowsList()
{
    const QString tmp = m_windowsListPath + QStringLiteral(".tmp");
    QFile f(tmp);
    if (!f.open(QIODevice::WriteOnly | QIODevice::Text | QIODevice::Truncate))
        return;

    const auto stack = KWin::effects->stackingOrder();
    for (KWin::EffectWindow *w : stack) {
        if (!w || !w->isNormalWindow()) continue;
        if (w->isDesktop() || w->isDock()) continue;

        QString uuid = w->internalId().toString(QUuid::WithoutBraces);
        QString cls  = w->windowClass();
        QString cap  = w->caption();
        if (cap.isEmpty()) cap = cls;
        /* Tabs/newlines would corrupt the line-oriented format. */
        const auto sanitize = [](QString &s) {
            s.replace(QChar('\t'), QChar(' '));
            s.replace(QChar('\n'), QChar(' '));
            s.replace(QChar('\r'), QChar(' '));
        };
        sanitize(cls);
        sanitize(cap);

        f.write(uuid.toUtf8());
        f.write("\t");
        f.write(cls.toUtf8());
        f.write("\t");
        f.write(cap.toUtf8());
        f.write("\n");
    }
    f.close();
    QFile::remove(m_windowsListPath);
    QFile::rename(tmp, m_windowsListPath);
}

/* ── Window redirection ───────────────────────────────────────────── */

void AppGraderEffect::redirectWindow(KWin::EffectWindow *w)
{
    if (!w) return;
    if (m_windows.find(w) != m_windows.end()) return;
    if (!m_lut || !m_shader || !m_shader->isValid()) return;
    if (!shouldGrade(w)) return;

    redirect(w);
    setShader(w, m_shader.get());
    m_windows.insert(w);
}

/* Per-window geometry hook: KWin doesn't fire windowAdded again when a
 * window is dragged onto another monitor, so without this we'd never
 * pick it up until the user toggled the monitor combo. UniqueConnection
 * makes repeated calls (startup vs. windowAdded vs. reEvaluate) safe. */
void AppGraderEffect::watchGeometry(KWin::EffectWindow *w)
{
    if (!w) return;
    connect(w, &KWin::EffectWindow::windowFrameGeometryChanged,
            this, &AppGraderEffect::onWindowGeometryChanged,
            Qt::UniqueConnection);
}

void AppGraderEffect::redirectAllWindows()
{
    if (!m_lut || !m_shader || !m_shader->isValid()) return;

    const auto stack = KWin::effects->stackingOrder();
    for (KWin::EffectWindow *w : stack) {
        watchGeometry(w);
        redirectWindow(w);
    }
}

/* Called when m_activeTarget might have changed: drop redirections for
 * windows that no longer match, add redirections for windows that do. */
void AppGraderEffect::reEvaluateRedirections()
{
    /* Drop windows that should no longer be graded. */
    for (auto it = m_windows.begin(); it != m_windows.end();) {
        if (!shouldGrade(*it)) {
            unredirect(*it);
            it = m_windows.erase(it);
        } else {
            ++it;
        }
    }
    /* Pick up newly-matching windows. */
    redirectAllWindows();

    KWin::effects->addRepaintFull();
}

void AppGraderEffect::onWindowAdded(KWin::EffectWindow *w)
{
    watchGeometry(w);
    redirectWindow(w);
    writeWindowsList();
}

void AppGraderEffect::onWindowDeleted(KWin::EffectWindow *w)
{
    m_windows.erase(w);
    writeWindowsList();
}

/* Fires every frame during a drag, so keep this cheap: only act when the
 * grade-eligibility actually flipped (e.g. window crossed a monitor edge
 * and is now/no-longer on the targeted output, or a different
 * window-targeted UUID became visible). */
void AppGraderEffect::onWindowGeometryChanged(KWin::EffectWindow *w,
                                              const QRectF &)
{
    if (!w) return;
    if (!m_lut || !m_shader || !m_shader->isValid()) return;

    const bool isRedirected = m_windows.find(w) != m_windows.end();
    const bool wantRedirect = shouldGrade(w);
    if (wantRedirect == isRedirected) return;

    if (wantRedirect) {
        redirect(w);
        setShader(w, m_shader.get());
        m_windows.insert(w);
    } else {
        unredirect(w);
        m_windows.erase(w);
    }
    KWin::effects->addRepaintFull();
}

/* ── File watcher ─────────────────────────────────────────────────── */

void AppGraderEffect::onLutFileChanged()
{
    /* Re-add the file path if the editor did atomic rename-replace and
     * QFileSystemWatcher dropped the inode. */
    if (QFile::exists(m_lutPath) && !m_watcher->files().contains(m_lutPath))
        m_watcher->addPath(m_lutPath);

    const bool hadLut = (bool)m_lut;
    loadLutFromFile();

    /* If we just got our first valid LUT, redirect every window now. */
    if (m_lut && !hadLut)
        redirectAllWindows();

    if (m_lut)
        KWin::effects->addRepaintFull();
}

void AppGraderEffect::onActiveTargetFileChanged()
{
    if (QFile::exists(m_activeTargetPath)
        && !m_watcher->files().contains(m_activeTargetPath))
        m_watcher->addPath(m_activeTargetPath);

    /* Always re-evaluate, even if the file's content didn't change. The
     * Reapply button in the app rewrites this file with the same content
     * specifically to trigger this path as a recovery for cases where
     * the per-window geometry hook missed something (e.g. a fullscreen
     * client moved its surface programmatically). The cost is just one
     * pass over the window list. */
    readActiveTarget();
    reEvaluateRedirections();
}

/* ── Per-screen pre-paint ─────────────────────────────────────────── */

/* If noise is non-zero we need a fresh frame each cycle so the grain
 * actually animates; otherwise we only repaint on data change. */
void AppGraderEffect::prePaintScreen(KWin::ScreenPrePaintData &data,
                                     std::chrono::milliseconds presentTime)
{
    KWin::OffscreenEffect::prePaintScreen(data, presentTime);
    /* Only force continuous repaints for *animated* noise. Static noise is
     * deterministic per pixel so it doesn't need redrawing every frame. */
    if (m_spatial.noise_amount > 1.0f / 255.0f && !m_spatial.noise_static)
        KWin::effects->addRepaintFull();
}

/* ── Per-window draw hook ─────────────────────────────────────────── */

void AppGraderEffect::drawWindow(const KWin::RenderTarget &renderTarget,
                                  const KWin::RenderViewport &viewport,
                                  KWin::EffectWindow *w,
                                  int mask,
                                  const KWin::Region &deviceRegion,
                                  KWin::WindowPaintData &data)
{
    const bool active = m_lut && m_windows.find(w) != m_windows.end();

    if (active) {
        glActiveTexture(GL_TEXTURE1);
        m_lut->bind();
        glActiveTexture(GL_TEXTURE0);

        /* Push spatial uniforms each frame — cheap, and lets us track value
         * changes without a separate "shader dirty" flag. */
        KWin::ShaderBinder binder(m_shader.get());
        QSize sz = renderTarget.size();   /* screen framebuffer size in pixels */
        m_shader->setUniform("appgrader_screen_w",         (float)sz.width());
        m_shader->setUniform("appgrader_screen_h",         (float)sz.height());
        m_shader->setUniform("appgrader_vig_amount",       m_spatial.vignette_amount);
        m_shader->setUniform("appgrader_vig_distance",     m_spatial.vignette_distance);
        m_shader->setUniform("appgrader_noise_amount",     m_spatial.noise_amount);
        m_shader->setUniform("appgrader_noise_color",      m_spatial.noise_color);
        m_shader->setUniform("appgrader_noise_scale",      m_spatial.noise_scale);
        m_shader->setUniform("appgrader_sharpen_amount",   m_spatial.sharpen_amount);
        m_shader->setUniform("appgrader_clarity_amount",   m_spatial.clarity_amount);
        m_shader->setUniform("appgrader_noise_static",
            m_spatial.noise_static ? 1.0f : 0.0f);
        m_shader->setUniform("appgrader_noise_seed",       m_spatial.noise_seed);
        m_shader->setUniform("appgrader_bloom_amount",     m_spatial.bloom_amount);
        m_shader->setUniform("appgrader_bloom_threshold",  m_spatial.bloom_threshold);
        m_shader->setUniform("appgrader_bloom_radius",     m_spatial.bloom_radius);
        m_shader->setUniform("appgrader_time",
            (float)(m_clock.elapsed() / 1000.0));
    }

    KWin::OffscreenEffect::drawWindow(renderTarget, viewport, w, mask, deviceRegion, data);

    if (active) {
        glActiveTexture(GL_TEXTURE1);
        glBindTexture(GL_TEXTURE_3D, 0);
        glActiveTexture(GL_TEXTURE0);
    }
}

#include "AppGraderEffect.moc"
